#!/bin/true # this file is not supposed to be called directly

function layer_install() {

	# install a systemd service to tune bcache on boot, also activate it now

	cat <<-EOF | sudo tee /lib/systemd/system/tune-bcache.service >/dev/null
	[Unit]
	Description=Tuning of bcache device settings
	After=systemd-udev-settle.service
	
	[Service]
	Type=oneshot
	ExecStart=/usr/local/bin/tune-bcache
	
	[Install]
	WantedBy=multi-user.target
	EOF

	cat <<-EOF | sudo tee /usr/local/bin/tune-bcache >/dev/null
	#!/usr/bin/python3
	
	# Generated by Foundation Cloud Engine
	
	import glob
	
	TUNABLES_TABLE = {
	    '/sys/block/bcache*/bcache/{}': {
	        'sequential_cutoff': '0',
	        'writeback_percent': '10',
	    },
	    '/sys/fs/bcache/*/{}': {
	        'congested_read_threshold_us': '0',
	        'congested_write_threshold_us': '0',
	    },
	}
	
	for globstring, tunables in TUNABLES_TABLE.items():
	    for tunable, value in tunables.items():
	        for path in glob.glob(globstring.format(tunable)):
	            print('Tuning {}: {}'.format(path, value))
	            with open(path, 'w') as fp:
	                fp.write(value)
	EOF

	sudo chmod +x /usr/local/bin/tune-bcache
	sudo systemctl daemon-reload
	sudo systemctl enable tune-bcache.service
	sudo systemctl start tune-bcache.service

}

function layer_uninstall() {

	sudo systemctl stop tune-bcache.service
	sudo rm -f /lib/systemd/system/tune-bcache.service
	sudo rm -f /usr/local/bin/tune-bcache
	sudo systemctl daemon-reload

}

